main/src/Entity/Ingredient.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IngredientRepository")
 */
class Ingredient
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="smallint")
     */
    private $type;

    const TYPE_OPTIC = 1;
    const TYPE_PUMPED = 2;
    const TYPES = [
        'Optic' => self::TYPE_OPTIC,
        'Pumped' => self::TYPE_PUMPED,
    ];

    /**
     * @ORM\Column(type="smallint")
     */
    private $viscosity;

    /**
     * @ORM\Column(type="smallint")
     */
    private $abv;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function getTypeAsString(): string
    {
        return array_flip(self::TYPES)[$this->type];
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getViscosity(): ?int
    {
        return $this->viscosity;
    }

    public function setViscosity(int $viscosity): self
    {
        $this->viscosity = $viscosity;

        return $this;
    }

    public function getAbv(): ?int
    {
        return $this->abv;
    }

    public function setAbv(int $abv): self
    {
        $this->abv = $abv;

        return $this;
    }
}

main/src/Form/IngredientType.php
<?php

namespace App\Form;

use App\Entity\Ingredient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IngredientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
            ])
            ->add('type', ChoiceType::class, [
                'choices'  => Ingredient::TYPES,
                'expanded' => true,
                'required' => true,
            ])
            ->add('viscosity', IntegerType::class, [
                'attr' => [
                    'min' => 0,
                    'max' => 10,
                ],
                'required' => true,
            ])
            ->add('abv', PercentType::class, [
                'label' => 'ABV %',
                'attr' => [
                    'min' => 0,
                    'max' => 10,
                ],
                'required' => true,
            ])
            ->add('save', SubmitType::class, ['label' => 'Save Ingredient'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
            'data_class' => Ingredient::class,
            ]
        );
    }
}

main/src/Controller/IngredientsController.php
<?php

namespace App\Controller;

use App\Entity\Ingredient;
use App\Form\IngredientType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IngredientsController extends AbstractController
{
    /**
     * @Route("/ingredients", name="ingredients")
     */
    public function ingredients()
    {
        return $this->render('ingredients.html.twig', [
            'ingredients' => $this->getDoctrine()->getRepository(Ingredient::class)->findAll(),
        ]);
    }

    /**
     * @Route("/ingredients/add", name="ingredients_add")
     */
    public function ingredientsAdd(Request $request)
    {
        return $this->handleAddOrEdit($request, new Ingredient());
    }

    /**
     * @Route("/ingredients/edit/{ingredientId}", name="ingredients_edit")
     */
    public function ingredientsEdit(Request $request, int $ingredientId)
    {
        // Find the ingredient
        $ingredient = $this->getDoctrine()->getRepository(Ingredient::class)->find($ingredientId);
        if (is_null($ingredient)){
            $this->addFlash('error', 'Sorry, we couldn\'t find the ingredient you wanted.');
            return $this->redirectToRoute('ingredients');
        }

        return $this->handleAddOrEdit($request, $ingredient);
    }

    private function handleAddOrEdit(Request $request, Ingredient $ingredient){
        // Create form
        $form = $this->createForm(IngredientType::class, $ingredient);

        // Handle form submission
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // Save the entity
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ingredient);
            $entityManager->flush();

            $this->addFlash('success', 'Your ingredient, '.$ingredient->getName().', has been saved.');
            return $this->redirectToRoute('ingredients');
        }

        return $this->render('ingredients-add.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

main/src/Controller/MenuController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MenuController extends AbstractController
{
    /**
     * @Route("/", name="menu")
     */
    public function number()
    {
        $number = random_int(0, 100);

        return $this->render('menu.html.twig', [
            'number' => $number,
        ]);
    }
}

main/templates/_layout/base.html.twig
<!doctype html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">

    {# Favicon and App icons #}
    <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('/icons/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('/icons//apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('/icons//apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('/icons//apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('/icons//apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('/icons//apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('/icons//apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('/icons//apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('/icons//apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{{ asset('/icons//android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('/icons//favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('/icons//favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('/icons//favicon-16x16.png') }}">
    <link rel="manifest" href="{{ asset('/icons//manifest.json') }}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ asset('/icons//ms-icon-144x144.png') }}">
    <meta name="theme-color" content="#ffffff">

    <title>{% block title %}tipplebot!{% endblock %}</title>

	{% block stylesheets %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/solid.css" integrity="sha384-osqezT+30O6N/vsMqwW8Ch6wKlMofqueuia2H7fePy42uC05rm1G+BUPSd2iBSJL" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/fontawesome.css" integrity="sha384-BzCy2fixOYd0HObpx3GMefNqdbA7Qjcc91RgYeDjrHTIEXqiF00jKvgQG0+zY/7I" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
        <link rel="stylesheet" href="{{ asset('build/app.css') }}">
	{% endblock %}
</head>
<body class="">
<div class="page">
    <div class="page-main">
        <div class="header py-4">
            <div class="container">
                <div class="d-flex">
                    <a class="header-brand" href="#" style="color: #e0022f;">
                        <i class="fas fa-cocktail"></i> tipplebot
                    </a>
                    <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                        <span class="header-toggler-icon"></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg order-lg-first">
                        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">

                            <li class="nav-item">
                                <a href="{{ path('menu') }}" class="nav-link"><i class="fas fa-cocktail"></i> Menu</a>
                            </li>

                            <li class="nav-item">
                                <a href="{{ path('ingredients') }}" class="nav-link"><i class="fas fa-wine-bottle"></i> Ingredients</a>
                            </li>

                            <li class="nav-item">
                                <a href="#" class="nav-link"><i class="fas fa-clipboard-list "></i> Stock</a>
                            </li>

                            <li class="nav-item">
                                <a href="#" class="nav-link"><i class="fas fa-file-alt"></i> Recipes</a>
                            </li>

                            {# Example drop down if we want it for later #}
                            {#<li class="nav-item">#}
                                {#<a href="javascript:void(0)" class="nav-link" data-toggle="dropdown"><i class="fe fe-box"></i> Interface</a>#}
                                {#<div class="dropdown-menu dropdown-menu-arrow">#}
                                    {#<a href="./cards.html" class="dropdown-item ">Cards design</a>#}
                                    {#<a href="./charts.html" class="dropdown-item ">Charts</a>#}
                                    {#<a href="./pricing-cards.html" class="dropdown-item ">Pricing cards</a>#}
                                {#</div>#}
                            {#</li>#}

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="my-3 my-md-5">
			{% block body %}{% endblock %}
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row align-items-center flex-row-reverse">
                <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
                    <a href="https://gitlab.com/tipplebot">tipplebox</a> is an open source project, made with <i class="fas fa-cocktail"></i> by Luke Cousins. UI theme by <a href="https://codecalm.net" target="_blank">codecalm.net</a>.
                </div>
            </div>
        </div>
    </footer>
</div>

{% block javascripts %}
    <script src="{{ asset('build/app.js') }}"></script>

    <script>
		requirejs.config({
			baseUrl: '.'
		});
    </script>
{% endblock %}

</body>
</html>

main/templates/ingredients-add.html.twig
{% extends '_layout/base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Add Ingredient</h3>
					</div>

					<div class="card-body">
						{{ form_start(form) }}
						{{ form_widget(form) }}
						{{ form_end(form) }}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

main/templates/ingredients.html.twig
{% extends '_layout/base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Ingredients</h3>
						<div class="card-options">
							<a href="{{ path('ingredients_add') }}" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Add</a>
						</div>
					</div>

					{% if ingredients|length > 0 %}
					<div class="table-responsive">
						<table class="table card-table table-vcenter text-nowrap">
							<thead>
							<tr>
								<th>Name</th>
								<th>Type</th>
								<th>Viscosity</th>
								<th>ABV</th>
								<th class="text-right">Actions</th>
							</tr>
							</thead>
							<tbody>
							{% for i in ingredients %}
								<tr>
									<td>{{ i.name }}</td>
									<td>{{ i.typeAsString }}</td>
									<td>{{ i.viscosity }} / 10</td>
									<td>{{ i.abv }}%</td>
									<td class="text-right"><a href="{{ path('ingredients_edit', { 'ingredientId': i.id }) }}" class="btn btn-primary btn-sm"><i class="fas fa-pencil-alt"></i> Edit</a></td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
					{% else %}
						<div class="card-body">There are no ingredients yet. <a href="{{ path('ingredients_add') }}">Add one</a>.</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

main/templates/menu.html.twig
{% extends '_layout/base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Your lucky number is {{ number }}</h3>
					</div>
					<div class="table-responsive">
						<table class="table card-table table-vcenter text-nowrap">
							<thead>
							<tr>
								<th class="w-1">No.</th>
								<th>Invoice Subject</th>
								<th>Client</th>
								<th>VAT No.</th>
								<th>Created</th>
								<th>Status</th>
								<th>Price</th>
								<th></th>
								<th></th>
							</tr>
							</thead>
							<tbody>
							<tr>
								<td><span class="text-muted">001401</span></td>
								<td><a href="invoice.html" class="text-inherit">Design Works</a></td>
								<td>
									Carlson Limited
								</td>
								<td>
									87956621
								</td>
								<td>
									15 Dec 2017
								</td>
								<td>
									<span class="status-icon bg-success"></span> Paid
								</td>
								<td>$887</td>
								<td class="text-right">
									<a href="javascript:void(0)" class="btn btn-secondary btn-sm">Manage</a>
									<div class="dropdown">
										<button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
									</div>
								</td>
								<td>
									<a class="icon" href="javascript:void(0)">
										<i class="fe fe-edit"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td><span class="text-muted">001402</span></td>
								<td><a href="invoice.html" class="text-inherit">UX Wireframes</a></td>
								<td>
									Adobe
								</td>
								<td>
									87956421
								</td>
								<td>
									12 Apr 2017
								</td>
								<td>
									<span class="status-icon bg-warning"></span> Pending
								</td>
								<td>$1200</td>
								<td class="text-right">
									<a href="javascript:void(0)" class="btn btn-secondary btn-sm">Manage</a>
									<div class="dropdown">
										<button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
									</div>
								</td>
								<td>
									<a class="icon" href="javascript:void(0)">
										<i class="fe fe-edit"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td><span class="text-muted">001403</span></td>
								<td><a href="invoice.html" class="text-inherit">New Dashboard</a></td>
								<td>
									Bluewolf
								</td>
								<td>
									87952621
								</td>
								<td>
									23 Oct 2017
								</td>
								<td>
									<span class="status-icon bg-warning"></span> Pending
								</td>
								<td>$534</td>
								<td class="text-right">
									<a href="javascript:void(0)" class="btn btn-secondary btn-sm">Manage</a>
									<div class="dropdown">
										<button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
									</div>
								</td>
								<td>
									<a class="icon" href="javascript:void(0)">
										<i class="fe fe-edit"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td><span class="text-muted">001404</span></td>
								<td><a href="invoice.html" class="text-inherit">Landing Page</a></td>
								<td>
									Salesforce
								</td>
								<td>
									87953421
								</td>
								<td>
									2 Sep 2017
								</td>
								<td>
									<span class="status-icon bg-secondary"></span> Due in 2 Weeks
								</td>
								<td>$1500</td>
								<td class="text-right">
									<a href="javascript:void(0)" class="btn btn-secondary btn-sm">Manage</a>
									<div class="dropdown">
										<button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
									</div>
								</td>
								<td>
									<a class="icon" href="javascript:void(0)">
										<i class="fe fe-edit"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td><span class="text-muted">001405</span></td>
								<td><a href="invoice.html" class="text-inherit">Marketing Templates</a></td>
								<td>
									Printic
								</td>
								<td>
									87956621
								</td>
								<td>
									29 Jan 2018
								</td>
								<td>
									<span class="status-icon bg-danger"></span> Paid Today
								</td>
								<td>$648</td>
								<td class="text-right">
									<a href="javascript:void(0)" class="btn btn-secondary btn-sm">Manage</a>
									<div class="dropdown">
										<button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
									</div>
								</td>
								<td>
									<a class="icon" href="javascript:void(0)">
										<i class="fe fe-edit"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td><span class="text-muted">001406</span></td>
								<td><a href="invoice.html" class="text-inherit">Sales Presentation</a></td>
								<td>
									Tabdaq
								</td>
								<td>
									87956621
								</td>
								<td>
									4 Feb 2018
								</td>
								<td>
									<span class="status-icon bg-secondary"></span> Due in 3 Weeks
								</td>
								<td>$300</td>
								<td class="text-right">
									<a href="javascript:void(0)" class="btn btn-secondary btn-sm">Manage</a>
									<div class="dropdown">
										<button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
									</div>
								</td>
								<td>
									<a class="icon" href="javascript:void(0)">
										<i class="fe fe-edit"></i>
									</a>
								</td>
							</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}